scrape_configs:
- job_name: prometheus
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets: ['localhost:9090']

- job_name: cadvisor
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: node_exporter
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - 10.10.10.168:9100

